#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/jtrindade/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

fbsetbg /home/jtrindade/aviamf9.jpg


gnome-settings-daemon &
gnome-sound-applet &
exec fluxbox


# or if you want to keep a log:
# exec fluxbox -log "/home/jtrindade/.fluxbox/log"

